version: '3.8'

services:
  app:
    build:
      context: .

  nginx:
    image: nginx
    ports:
    - 80:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./static:/usr/src/text_analyzer/static
    - ./media:/usr/src/text_analyzer/media
    depends_on:
      - app